name: &name haskell-playground
version: 0.1.0.0
license: BSD3
maintainer: xnuk
copyright: 2018 @xnuk
category: Web
extra-source-files:
- README.md
- LICENSE

github: xnuk/haskell-playground


default-extensions:
  - RecursiveDo
  - MultiParamTypeClasses
  - FunctionalDependencies
  - RankNTypes
  - ExistentialQuantification
  - ScopedTypeVariables
  - ImplicitParams
  - KindSignatures
  - BangPatterns
  - NamedFieldPuns
  - TypeFamilies
  - StandaloneDeriving
  - UnicodeSyntax
  - LiberalTypeSynonyms
  - TypeOperators
  - RecordWildCards
  - DisambiguateRecordFields
  - GADTs
  - InstanceSigs
  - PackageImports
  - QuasiQuotes
  - TupleSections
  - MultiWayIf
  - LambdaCase
  - DeriveFunctor
  - NegativeLiterals
  - BinaryLiterals
  - ExplicitNamespaces
  - PatternSynonyms
  - ApplicativeDo
  - DuplicateRecordFields
  - BlockArguments
  - NumericUnderscores

library:
  source-dirs: src
  other-modules: Prelude
  dependencies:
    - base >= 4.7 && < 5
    - conduit
    - wreq
    - req
    - microlens-platform
    - yaml
    - pcre-heavy
    - aeson
    - http-client-tls
    - attoparsec
    - bytestring
    - text
    - data-default-class
    - containers
    - unordered-containers
    - string-conversions
    - transformers
    - raw-strings-qq
    - interpolate
    - lens-aeson
    - lens
    - aeson
    - rawfilepath
  ghc-options: -O2 -Wall -fwarn-tabs -fwarn-incomplete-record-updates -fwarn-monomorphism-restriction -fwarn-unused-do-bind -Werror

executables:
  haskell-playground:
    main: Main.hs
    dependencies:
      - base >= 4.7 && < 5
      - *name
    ghc-options: -O2 -Wall -fwarn-tabs -fwarn-incomplete-record-updates -fwarn-monomorphism-restriction -fwarn-unused-do-bind -Werror
