_foo_bar_baz:
  # To update cache:
  #     git rev-parse HEAD > .circleci/cache-counter
  - &stack_cache_key r{{ checksum ".circleci/cache-counter" }}-stack-{{ arch }}-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}

version: 2.1
jobs:
  build:
    docker:
      - image: haskell:latest

    steps:
      - checkout

      - restore_cache:
          keys:
            - *stack_cache_key

      - run: apt-get update -y && apt-get install curl libpcre++-dev -y
      - run: ./update-stack.hs

      - run: stack setup
      - run: stack install hlint
      - run: stack exec env
      - run: stack build --only-snapshot

      - save_cache:
          key: *stack_cache_key
          paths:
            - .stack-work
            - ../.stack

      - run: stack build
      - run: hlint .

workflows:
  build:
    jobs:
      - build

